[package]
name = "v4l-tui"
description = "TUI alternative to v4l-ctl or cameractrls"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-only"
publish = false

[workspace]
members = ["xtask"]

[workspace.dependencies]
ratatui = { version = "0.30", default-features = false, features = ["crossterm", "layout-cache"] }

[dependencies]
anyhow = "1"
const_format = "0.2"
itertools = "0.15"
ratatui.workspace = true
unicode-consts = "0.2"
v4l = "0.14"

[patch.crates-io]
v4l = { git = "https://github.com/sermuns/libv4l-rs" }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
uninlined_format_args = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
needless_pass_by_value = "allow"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true
