[package]
name = "cameractrls-rs"
description = "TUI alternative to v4l-ctl or cameractrls"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
color-eyre = "0.6"
const_format = "0.2"
itertools = "0.15"
ratatui = "0.30"
unicode-consts = "0.2"
v4l = "0.14"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
uninlined_format_args = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
needless_pass_by_value = "allow"
